routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminAuth\LoginController;
use App\Http\Controllers\AdminAuth\ForgotPasswordController;
use App\Http\Controllers\AdminAuth\ResetPasswordController;
use App\Http\Controllers\AdminAuth\ChangePasswordController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Frontend\PageController;
use App\Http\Controllers\Admin\CMS\InitiativeController;
use App\Http\Controllers\Admin\CMS\CampaignController;
use App\Http\Controllers\Admin\CMS\NewsController;
use App\Http\Controllers\Admin\CMS\PressReleaseController;
use App\Http\Controllers\Admin\CMS\SiteSettingController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('frontend.index');
// });



Route::get('/',  [PageController::class, 'index'])->name('home');
Route::get('/what-we-do', [PageController::class, 'whatWeDo'])->name('pages.what-we-do');
Route::get('/who-we-are', [PageController::class, 'whoWeAre'])->name('pages.who-we-are');
Route::get('policy', [PageController::class, 'policy'])->name('pages.policy');
Route::get('/initiatives', [PageController::class, 'initiatives'])->name('pages.initiatives');
Route::get('/campaigns', [PageController::class, 'campaigns'])->name('pages.campaigns');
// Route::get('/press-releases', [PageController::class, 'pressReleases'])->name('pages.press-releases');
// Route::get('/in-the-news', [PageController::class, 'inTheNewsListing'])->name('pages.in-the-news');
Route::get('/latest-news', [PageController::class, 'latestNewsListing'])->name('pages.latest-news');


Route::get('/who-we-are', [PageController::class, 'whoWeAre'])->name('pages.who-we-are');
Route::get('privacy-policy', [PageController::class, 'privacyPolicy'])->name('pages.privacy.policy');
Route::get('cookie-policy', [PageController::class, 'cookiePolicy'])->name('pages.cookie.policy');
Route::get('terms-of-use', [PageController::class, 'termsOfUse'])->name('pages.terms.of.use');
Route::get('/press-releases/{media:slug}', [PageController::class, 'pressRelease'])->name('pages.press-release');
Route::get('/in-the-news/{media:slug}', [PageController::class, 'inTheNews'])->name('pages.in-the-news-detail');
Route::get('/latest-news/{media:slug}', [PageController::class, 'latestNews'])->name('pages.latest-news-detail');

Route::get('initiatives/{initiative:slug}', [PageController::class, 'initiative'])->name('pages.initiative');
Route::get('initiatives/{initiative:slug}/{campaign:slug}', [PageController::class, 'campaign'])->name('pages.campaign');
Route::get('initiatives/{initiative:slug}/{campaign:slug}/{media:slug}', [PageController::class, 'mediaCenterDetail'])->name('pages.media-center-detail');

Route::get('/contact', [PageController::class, 'contact'])->name('pages.contact');
Route::post('/contact', [PageController::class, 'contactMail'])->name('pages.contact-mail');


// Auth::routes();
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['auth:admin']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::prefix('/admin')->name('admin.')->group(function () {
    Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('login', [LoginController::class, 'login'])->name('login');
    // password reset routes
    Route::post('/password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
    Route::get('/password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
    Route::post('/password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');
    Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
});

Route::prefix('/admin')->middleware('auth:admin')->name('admin.')->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::post('logout', [LoginController::class, 'logout'])->name('logout');
    Route::get('/change-password', [ChangePasswordController::class, 'changePassword'])->name('change-password.edit');
    Route::put('/change-password', [ChangePasswordController::class, 'updatePassword'])->name('change-password.update');
    Route::resource('initiatives', InitiativeController::class)->except(['show']);
    Route::resource('initiatives.campaigns', CampaignController::class)->except(['show']);
    Route::resource('press-releases', PressReleaseController::class);
    Route::resource('news', NewsController::class);
});

Route::prefix('/admin')->middleware('auth:admin')->name('admin.')->group(function () {
    Route::get('site-settings/edit', [SiteSettingController::class, 'edit'])->name('site-settings.edit');
    Route::post('site-settings/store', [SiteSettingController::class, 'store'])->name('site-settings.store');
    Route::put('site-settings/{generalSettings}/update', [SiteSettingController::class, 'update'])->name('site-settings.update');
});

app/Models/SiteSetting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SiteSetting extends Model
{
    use HasFactory;

    protected $guarded = [];
}

app/Http/Controllers/Admin/CMS/CampaignController.php
<?php

namespace App\Http\Controllers\Admin\CMS;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Campaign;
use App\Models\Initiative;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;

class CampaignController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Initiative $initiative)
    {
        $campaigns = $initiative->campaigns;
        return view('admin.cms.campaigns.index', compact('campaigns', 'initiative'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Initiative $initiative)
    {
        return view('admin.cms.campaigns.create', compact('initiative'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Initiative $initiative)
    {
        $data = $request->validate([
            'name' => ['required', 'string', 'max:255', Rule::unique('campaigns')->where(function ($query) use ($initiative) {
                return $query->where('initiative_id', $initiative->id);
            })],
            'header_image' => 'required|image',
            'feature_image' => 'required|image',
            'excerpt' => 'required|string',
            'body' => 'required',
            'meta_title' => 'required',
            'meta_keywords' => 'nullable',
            'meta_description' => 'nullable',
        ]);

        $data['header_image'] = uploadFile($request->file('header_image'));
        $data['feature_image'] = uploadFile($request->file('feature_image'));

        $data['slug'] = \Str::slug($data['name']);
        $initiative->campaigns()->create($data);
        $request->session()->flash('message', 'Campaign created successfully');
        $request->session()->flash('alert-class', 'alert alert-success');
        return redirect()->route('admin.initiatives.campaigns.index', $initiative->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Initiative $initiative, Campaign $campaign)
    {
        return view('admin.cms.campaigns.edit', compact('campaign', 'initiative'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Initiative $initiative, Campaign $campaign)
    {
        $data = $request->validate([
            'name' => ['required', 'string', 'max:255', Rule::unique('campaigns')->where(function ($query) use ($initiative) {
                return $query->where('initiative_id', $initiative->id);
            })->ignore($campaign->id, 'id')],
            'header_image' => 'nullable|image',
            'feature_image' => 'nullable|image',
            'excerpt' => 'required|string',
            'body' => 'required',
            'meta_title' => 'required',
            'meta_keywords' => 'nullable',
            'meta_description' => 'nullable',
        ]);

        if ($request->header_image) {
            $data['header_image'] = uploadFile($request->file('header_image'));
        } else {
            $data['header_image'] = $campaign->header_image;
        }

        if ($request->feature_image) {
            $data['feature_image'] = uploadFile($request->file('feature_image'));
        } else {
            $data['feature_image'] = $campaign->feature_image;
        }

        $data['slug'] = \Str::slug($data['name']);

        $campaign->update($data);
        $request->session()->flash('message', 'Campaign updated successfully');
        $request->session()->flash('alert-class', 'alert alert-success');
        return redirect()->back();
    }

    public function destroy(Request $request, Initiative $initiative, Campaign $campaign)
    {
        Storage::delete('public/' . $campaign->header_image);
        $campaign->pressReleases()->detach();
        $campaign->delete();
        $request->session()->flash('message', 'Campaign deleted successfully');
        $request->session()->flash('alert-class', 'alert alert-danger');
        return redirect(route('admin.initiatives.campaigns.index', [$initiative]));
    }
}

app/Http/Controllers/Admin/CMS/InitiativeController.php
<?php

namespace App\Http\Controllers\Admin\CMS;

use App\Http\Controllers\Controller;
use App\Models\Initiative;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class InitiativeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $initiatives = Initiative::all();
        return view('admin.cms.initiatives.index', compact('initiatives'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.cms.initiatives.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'name' => 'required|string|max:255',
            'header_image' => 'required|image',
            'feature_image' => 'required|image',
            'excerpt' => 'required|string',
            'body' => 'required',
            'meta_title' => 'required',
            'meta_keywords' => 'nullable',
            'meta_description' => 'nullable',
        ]);

        $data['header_image'] = uploadFile($request->file('header_image'));
        $data['feature_image'] = uploadFile($request->file('feature_image'));

        $data['slug'] = \Str::slug($data['name']);
        Initiative::create($data);
        $request->session()->flash('message', 'Initiative created successfully');
        $request->session()->flash('alert-class', 'alert alert-success');
        return redirect(route('admin.initiatives.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Initiative $initiative)
    {
        return view('admin.cms.initiatives.edit', compact('initiative'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Initiative $initiative)
    {
        $data = $request->validate([
            'name' => 'required|string|max:255',
            'header_image' => 'nullable|image',
            'feature_image' => 'nullable|image',
            'excerpt' => 'required|string',
            'body' => 'required',
            'meta_title' => 'required',
            'meta_keywords' => 'nullable',
            'meta_description' => 'nullable',
        ]);

        if ($request->header_image) {
            $data['header_image'] = uploadFile($request->file('header_image'));
        } else {
            $data['header_image'] = $initiative->header_image;
        }

        if ($request->feature_image) {
            $data['feature_image'] = uploadFile($request->file('feature_image'));
        } else {
            $data['feature_image'] = $initiative->feature_image;
        }

        $data['slug'] = \Str::slug($data['name']);

        $initiative->update($data);
        $request->session()->flash('message', 'Initiative updated successfully');
        $request->session()->flash('alert-class', 'alert alert-success');
        return redirect(route('admin.initiatives.index'));
    }

    public function destroy(Initiative $initiative)
    {
        Storage::delete('public/' . $initiative->header_image);
        $initiative->delete();
        $request->session()->flash('message', 'Initiative deleted successfully');
        $request->session()->flash('alert-class', 'alert alert-danger');
        return redirect(route('admin.initiatives.index'));
    }
}

app/Http/Controllers/Admin/CMS/SiteSettingController.php
<?php

namespace App\Http\Controllers\Admin\CMS;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\SiteSetting;

class SiteSettingController extends Controller
{

    /**
     * Edit the form for editing the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit()
    {
        $siteSettings = SiteSetting::first();
        if ($siteSettings) {
            return view('admin.cms.site-settings.edit', compact('siteSettings'));
        } else {
            return view('admin.cms.site-settings.create');
        }
    }

    /**
     * Store the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $settings = SiteSetting::first();
        if ($settings) {
            update($request, $settings);
        }

        $data = $request->validate([
            'logo' => ['required', 'image'],
            'facebook_link' => ['nullable', 'url'],
            'linkedin_link' => ['nullable', 'url'],
            'youtube_link' => ['nullable', 'url'],
            'twitter_link' => ['nullable', 'url'],
            'email' => ['required', 'email'],
        ]);

        $data['logo'] = uploadFile($request->file('logo'));

        SiteSetting::create($data);

        $request->session()->flash('message', 'Site settings created successfully');
        $request->session()->flash('alert-class', 'alert alert-success');
        return redirect()->back();
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $settings = SiteSetting::first();

        $data = $request->validate([
            'logo' => ['nullable', 'image'],
            'facebook_link' => ['nullable', 'url'],
            'linkedin_link' => ['nullable', 'url'],
            'youtube_link' => ['nullable', 'url'],
            'twitter_link' => ['nullable', 'url'],
            'email' => ['required', 'email'],
        ]);

        if ($request->logo) {
            $data['logo'] = uploadFile($request->file('logo'));
        } else {
            $data['logo'] = $settings->logo;
        }

        $settings->update($data);


        $request->session()->flash('message', 'Site settings updated successfully');
        $request->session()->flash('alert-class', 'alert alert-success');
        return redirect()->back();
    }
}

resources/views/admin/cms/site-settings/create.blade.php
@extends('admin.layouts.layout')

@section('heading')
    <h4>
        <a href="{{ route('admin.home') }}">
            <i class="icon-arrow-left52 mr-2"></i>
        </a>
        <span class="font-weight-semibold">Home - General Settings</span>
    </h4>
@endsection

@section('breadcrumbs')
    <div class="breadcrumb">
        <a href="{{ route('admin.home') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
        <span class="breadcrumb-item">General Settings</span>
    </div>
@endsection

@section('content')
    @include('admin.partials.header')
    <div class="content">
        @include('common.partials.flash')

        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">Site Settings</h5>
            </div>

            <div class="card-body">
                <form action="{{ route('admin.site-settings.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label style="display: block;"
                            class="font-weight-semibold @error('logo') text-danger @enderror">Logo <span class="text-red">*</span>
                        </label>
                        <div class="d-inline-block" style="position: relative;margin-bottom: inherit;">
                        <input type="file" accept=".jpeg,.png,.bmp,.gif,.svg,.webp" name="logo" value="{{ old('logo') }}">
                        <span class="form-text text-muted">Accepted formats: jpeg, png, bmp, gif, svg, or webp</span>
                        @error('logo')
                            <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="font-weight-semibold @error('facebook_link') text-danger @enderror">Facebook Link</label>
                        <div class="form-group-feedback form-group-feedback-right">
                            <input type="text" name="facebook_link" value="{{ old('facebook_link') }}"
                                class="form-control @error('facebook_link') border-danger @enderror">
                            @error('facebook_link')
                            <div class="form-control-feedback text-danger">
                                <i class="icon-cancel-circle2"></i>
                            </div>
                            @enderror
                        </div>
                        @error('facebook_link')
                            <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label class="font-weight-semibold @error('linkedin_link') text-danger @enderror">Linkedin Link</label>
                        <div class="form-group-feedback form-group-feedback-right">
                            <input type="text" name="linkedin_link" value="{{ old('linkedin_link') }}"
                                class="form-control @error('linkedin_link') border-danger @enderror">
                            @error('linkedin_link')
                            <div class="form-control-feedback text-danger">
                                <i class="icon-cancel-circle2"></i>
                            </div>
                            @enderror
                        </div>
                        @error('linkedin_link')
                            <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label class="font-weight-semibold @error('youtube_link') text-danger @enderror">Youtube Link</label>
                        <div class="form-group-feedback form-group-feedback-right">
                            <input type="text" name="youtube_link" value="{{ old('youtube_link') }}"
                                class="form-control @error('youtube_link') border-danger @enderror">
                            @error('youtube_link')
                            <div class="form-control-feedback text-danger">
                                <i class="icon-cancel-circle2"></i>
                            </div>
                            @enderror
                        </div>
                        @error('youtube_link')
                            <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label class="font-weight-semibold @error('twitter_link') text-danger @enderror">Twitter Link</label>
                        <div class="form-group-feedback form-group-feedback-right">
                            <input type="text" name="twitter_link" value="{{ old('twitter_link') }}"
                                class="form-control @error('twitter_link') border-danger @enderror">
                            @error('twitter_link')
                            <div class="form-control-feedback text-danger">
                                <i class="icon-cancel-circle2"></i>
                            </div>
                            @enderror
                        </div>
                        @error('twitter_link')
                            <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label class="font-weight-semibold @error('email') text-danger @enderror">Email <span class="text-red">*</span></label>
                        <div class="form-group-feedback form-group-feedback-right">
                            <input type="email" name="email" value="{{ old('email') }}"
                                class="form-control @error('email') border-danger @enderror">
                            @error('email')
                            <div class="form-control-feedback text-danger">
                                <i class="icon-cancel-circle2"></i>
                            </div>
                            @enderror
                        </div>
                        @error('email')
                            <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">Submit <i class="icon-paperplane ml-2"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/cms/site-settings/edit.blade.php
@extends('admin.layouts.layout')

@section('heading')
    <h4>
        <a href="{{ route('admin.home') }}">
            <i class="icon-arrow-left52 mr-2"></i>
        </a>
        <span class="font-weight-semibold">Home - Site Settings</span>
    </h4>
@endsection

@section('breadcrumbs')
    <div class="breadcrumb">
        <a href="{{ route('admin.home') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
        <span class="breadcrumb-item">Site Settings</span>
    </div>
@endsection

@section('content')
    @include('admin.partials.header')
    <div class="content">
        @include('common.partials.flash')
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">Site Settings</h5>
            </div>
            <div class="card-body">
                <form action="{{ route('admin.site-settings.update', $siteSettings->id) }}" enctype="multipart/form-data" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label style="display: block;"
                            class="font-weight-semibold @error('logo') text-danger @enderror">Logo <span
                                class="text-red">*</span></label>
                        <div class="d-inline-block" style="position: relative;margin-bottom: inherit;">
                        @if($siteSettings->logo)
                            <div class="d-inline-block" style="position:relative;margin-bottom: inherit; ">
                                <img src="{{ asset('/storage/'.$siteSettings->logo) }}" height="100px" width="100px"/>
                            </div>
                        @else
                            <p>No Logo Found</p>
                        @endif
                        <input type="file" accept=".jpeg,.png,.bmp,.gif,.svg,.webp" name="logo">
                        <span class="form-text text-muted">Accepted formats: jpeg, png, bmp, gif, svg, or webp</span>
                        @error('logo')
                            <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="font-weight-semibold @error('facebook_link') text-danger @enderror">Facebook Link </label>
                        <div class="form-group-feedback form-group-feedback-right">
                            <input type="text" name="facebook_link" value="{{ old('facebook_link', $siteSettings->facebook_link) }}"
                                class="form-control @error('facebook_link') border-danger @enderror">
                            @error('facebook_link')
                            <div class="form-control-feedback text-danger">
                                <i class="icon-cancel-circle2"></i>
                            </div>
                            @enderror
                        </div>
                        @error('facebookLink')
                        <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label class="font-weight-semibold @error('linkedin_link') text-danger @enderror">Linkedin Link </label>
                        <div class="form-group-feedback form-group-feedback-right">
                            <input type="text" name="linkedin_link" value="{{ old('linkedin_link', $siteSettings->linkedin_link) }}"
                                class="form-control @error('linkedin_link') border-danger @enderror">
                            @error('linkedin_link')
                            <div class="form-control-feedback text-danger">
                                <i class="icon-cancel-circle2"></i>
                            </div>
                            @enderror
                        </div>
                        @error('linkedin_link')
                        <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label class="font-weight-semibold @error('youtube_link') text-danger @enderror">Youtube Link </label>
                        <div class="form-group-feedback form-group-feedback-right">
                            <input type="text" name="youtube_link" value="{{ old('youtube_link', $siteSettings->youtube_link) }}"
                                class="form-control @error('youtube_link') border-danger @enderror">
                            @error('youtube_link')
                            <div class="form-control-feedback text-danger">
                                <i class="icon-cancel-circle2"></i>
                            </div>
                            @enderror
                        </div>
                        @error('youtube_link')
                        <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label class="font-weight-semibold @error('twitter_link') text-danger @enderror">Twitter Link </label>
                        <div class="form-group-feedback form-group-feedback-right">
                            <input type="text" name="twitter_link" value="{{ old('twitter_link', $siteSettings->twitter_link) }}"
                                class="form-control @error('twitter_link') border-danger @enderror">
                            @error('twitter_link')
                            <div class="form-control-feedback text-danger">
                                <i class="icon-cancel-circle2"></i>
                            </div>
                            @enderror
                        </div>
                        @error('twitter_link')
                        <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label class="font-weight-semibold @error('email') text-danger @enderror">Email <span class="text-danger">*</span></label>
                        <div class="form-group-feedback form-group-feedback-right">
                            <input type="email" name="email" value="{{ old('email', $siteSettings->email) }}"
                                class="form-control @error('email') border-danger @enderror">
                            @error('email')
                            <div class="form-control-feedback text-danger">
                                <i class="icon-cancel-circle2"></i>
                            </div>
                            @enderror
                        </div>
                        @error('email')
                        <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">Submit <i class="icon-paperplane ml-2"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection